In [10]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
result = np.dot(A, B)

# A*Bの積を表示
print(result)

# 要素内の最大値を表示
print(f"要素の最大値は{result.max()}です")

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
要素の最大値は47です
