##演習3-1
* 行列の積(アダマール積)を計算して値を返す関数を定義し、複数の値を呼び出し結果を確認してください。

In [ ]:
import numpy as np

# アダマール積（要素同士の積を計算し返す関数を定義)
def calculate_hadamard_product(array_1, array_2):
    return array_1 * array_2


# 計算し、出力を行う
array_A = np.array([[1, 2, 3], [4, 5, 6]])
array_B = np.array([[1, 2, 3], [4, 5, 6]])
print(calculate_hadamard_product(array_A, array_B))

array_C = np.array([[7, 8, 9], [10, 11, 12]])
array_D = np.array([[6, 6, 6], [3, 3, 3]])
print(calculate_hadamard_product(array_C, array_D))

array_E = np.array([[1, 3, 5], [7, 9, 13]])
array_F = np.array([[13, 9, 7], [5, 3, 1]])
print(calculate_hadamard_product(array_E, array_F))



[[ 1  4  9]
 [16 25 36]]
[[42 48 54]
 [30 33 36]]
[[13 27 35]
 [35 27 13]]


##演習3-2
* 行列を転置(ヒント: .T)するメソッドを持つクラスを作成してください。コンストラクタにはその行列を渡し、クラス内で保持して転置メソッドで利用してください。


In [ ]:
import numpy as np

# クラスを定義
class Matrix:
    # コンストラクタを定義
    def __init__(self,matrix):
        self.matrix = matrix

    # 転置メソッドを定義
    def transposition(self):
        return self.matrix.T

# インスタンス化を行う
matrix = np.array([[1, 2, 3], [4, 5, 6]])
input =Matrix(matrix)

# 転置前と転置後をそれぞれ出力する
print(input.matrix)
print(input.transposition())

# print(matrix.transpose())
# print(np.transpose(matrix))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


##演習3-3
* 行列の要素を二乗してください

In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix ** 2)
# print(np.square(matrix))

[[ 1  4  9]
 [16 25 36]]


## 演習3-4
* 4×4の二次元配列を作成し、2行目から4行目まで、2列目から4列目までの3x3の部分配列を抽出してください。(スライシング)

In [ ]:
import numpy as np
matrix = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(matrix)

# 行列ともに2(インデックス:1)から4(インデックス:3)を抽出
matrix[1:4, 1:4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

## 演習3-5
* 1次元配列から奇数インデックスの要素を抽出してください。（ヒント: スライシングとストライド）

In [ ]:
import numpy as np
matrix = np.arange(10)
print(matrix)

# 初期値1から1個おきに抽出する
matrix[1::2]


[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

## 演習3-6
* 2次元配列（5×5）を1次元配列へ変換してください。
* その際、2次元配列はfor文×2を用いて作成してください。

In [17]:
import numpy as np

# 格納用のリストを定義
row = []
matrix = []

# リスト内に数値を格納
for i in range(5):
    for j in range(5):
         row.append(j)
    matrix.append(row)
    row = []

# ndarray形式に変換
array = np.array(matrix)

# 1次元配列に変換し出力
flat_array = np.ravel(array)
print(flat_array)


[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
